name: 'Download and Unarchive a Build Artifact'
description: 'Download a build artifact that was previously uploaded in the workflow by the RockLobster/archiving-upload-artifact action'
author: 'GitHub'

branding:
  icon: 'arrow-down'
  color: 'green'

inputs: 
  name:
    description: 'Artifact name'
    required: true
  path:
    description: 'Destination path'
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Download Archive
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: /tmp/RockLobster_download_archive
    - name: Unarchive
      run: |
        mkdir -p ${{ inputs.path }}
        unzip /tmp/RockLobster_download_archive/*.rTmpArchive.zip -d ${{ inputs.path }}
      shell: bash
    - name: Clean Up
      if: always()
      run: |
        rm -rf /tmp/RockLobster_download_archive
      shell: bash